= SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4
v1, 2023-01-18 : Initial readme
:icons: font
:experimental:
:toc:


*Équipe 4* : +
Bryce FUERTES, Thomas FALSIMAGNE, Alex JOLAS, James GRASSER, Nolan JACQUEMONT


== I. Contexte du projet

[.text-justify]
Le client, M. Boulle, a missionné le département GIM et ses étudiants pour mettre au point une tireuse à bière connectée. Dans une approche IOT pour l'industrie 4.0, le client souhaite disposer d'une machine connectée qui envoie des données de température, de niveau de bière et de puissance électrique à l’utilisateur. Pour cela, ces données doivent pouvoir être lues sur une application web ou un site web, disponible sur un téléphone ou un ordinateur, afin que l'utilisateur puisse disposer d'une interface intuitive pour contrôler sa tireuse. +

N'ayant pas la compétence nécessaire pour concevoir la partie applicative du projet, les étudiants du département GIM ont donc fait appel à nous pour la réaliser. À partir du cahier des charges qu'ils nous ont founi, nous devons donc développer une application répondant aux différents besoins spécifiés. 

== II. Acteurs de l'équipe projet 

[options="header,footer"]
|===
| Nom - Prénom  | Rôle         |  Tâches
| Nolan Jacquemont | Product Owner| Définit le produit et veille à ce que celui-ci réponde au besoin du département GIM.
| Thomas Falsimagne | Scrum Master | Réalise la répartition des tâches et s'assure de la bonne coopération des différents membres de l'équipe.
| Alex Jolas | Développeur FRONT-END | S'occupe du développement de l'interface FRONT-END de l'application.
| James Grasser | Développeur FRONT-END| S'occupe du développement de l'interface FRONT-END de l'application.
| Bryce Fuertes | Développeur FRONT-END | S'occupe du développement de l'interface FRONT-END de l'application.
|===

== III. Suivi du projet

[options="header,footer"]
|===
| Date    | Nom         |  Lien |                             Retour
| 16/01/2023 | BACKLOG PRODUIT| https://github.com/Falsimane/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4/issues |
| 16/01/2023 | Backlog sprint 1 | https://github.com/Falsimane/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4/milestone/2?closed=1 |
| 16/01/2023 | Backlog sprint 2 | https://github.com/Falsimane/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4/blob/main/Documentation/BacklogSprint2.adoc |
| 21/01/2023 | User Stories | https://github.com/Falsimane/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4/blob/main/Documentation/UserStories.adoc |
| 21/01/2023 | Documentation technique | https://github.com/Falsimane/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4/blob/main/Documentation/documentation_technique.adoc |
| 23/01/2023 | Documentation utilisateur | https://github.com/Falsimane/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4/blob/main/Documentation/documentation_utilisateur.adoc |
| 25/01/2023 | Cahier de tests | https://github.com/Falsimane/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4/blob/main/Documentation/CahierDeTests.adoc|
| 25/01/2023 | Sprintboard | https://github.com/users/Falsimane/projects/2/views/1 |
|===


== IV. Releases  

=== 1. Release sprint 1

[options="header,footer"]
|===
| Date |  Lien | Retour
| 22/01/2023 | https://github.com/Falsimane/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4/releases/tag/V1.0|
|===




=== 2. Release sprint 2

[options="header,footer"]
|===
| Date |  Lien | Retour
| 29/01/2023 | https://github.com/Falsimane/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4/releases/tag/v2.0 |
|===


== V. Sprint Review

=== 1. Sprint 1

==== 1.1. User Stories réalisées

NOTE: Les user stories sont disponibles dans le fichier UserStories.adoc présent dans le tableau de suivi du projet.

[options="header,footer"]
|===
| User Story | Nom de l'US| Retour
| 1 | Consulter la température de la bière à l’intérieur du fût.
| Cette user story a été réalisée et testée.
| 2 | Consulter le niveau de la tireuse à bière.|Cette user story a été réalisée et testée.
| 3 | Consulter la puissance de la tireuse à bière.|Cette user story a été réalisée et testée.
| 10 | Consulter l’état de la température.|Cette user story a été réalisée et testée.
| 11 | Consulter l’état du niveau de la bière.|Cette user story a été réalisée et testée.
| 12 | Consulter l’état de la puissance de la bière.|Cette user story a été réalisée et testée.
|===

==== 1.2. Difficultés rencontrées

[options="header,footer"]
|===
| US | Description de la difficulté | Solution
| 1 | La difficulté a été de trouver comment récupérer les données arrivant du broker MQTT en entrée, pour les envoyer vers un WebSocket en sortie. | La solution a été de déployer un node-red pour pouvoir pousser les données récupérer du broker vers un WebSocket, qui, nativement, n'est pas implémenté par le client.

| 2 |  |
| 3 |  |
| 10 |  |
| 11 |  |
| 12 |  |
|===


==== 1.3 Retour équipe projet

Ce premier sprint a été pour nous assez compliqué au départ, chaque membre de l'équipe ayant des compétences différentes, et ne connaissant pas forcément les technologies qui nous permettent maintenant de développer l'application. Il nous a donc fallu dans un premier temps faire quelques heures de formation, afin de pouvoir nous lancer réellement dans le projet. Cependant, nous terminons sur une bonne note. +

Effectivement, nous avons pu réaliser les user stories que nous avions définies pour le sprint 1. Nous sommes donc satisfaits de notre travail et sommes prêts à attaquer le sprint 2.

Vous trouverez toutes les indications dans le tableau de suivi de projet pour suivre notre avancée et pouvoir essayer notre application. La documentation technique vous permettra de comprendre comment l'application fonctionne et comment vous pouvez l'utiliser.

==== 1.4. Retour sprint semaine 3 EP

Documentation technique : o k (à versionner, dater, mettre nom équipe)
Manque doc ustilisateur

Backlog produit  : vous avez fait le backlog produit dans un doc appelé Users stories (TB) mais je dois retrouver ces users stories dans Github (cf. Vidéo) avec les critères, les tâches liées ...
Backlog de sprint :  je dois avoir une colonne avec les US traités dans le sprint puis 3 ou 4 colonnes (A faire, en cours, validation, terminé par ex) avec les issues (tâches) liées aux US. C'est un sprintBoard, le votre ne montre que les issues par les US liées. cf vidéo

 Cahier de tests à revoir (reprendre ce qui est fait dans les Users stories) avec une colonne validation, dans votre readme j'ai juste la liste des US notée validé.

J'ai une release à la fin du premier sprint c'est bien.

Continuez ainsi ... je devrais aussi avoir le balcklog sprint 2 (liste des US que vous allez traiter cette semaine).

CR ok



=== 2. Sprint 2

==== 2.1. Suivi du sprint

[options="header,footer"]
|===
| Date |  Nom | Lien | Retour
| 25/01/2023 |  Backlog sprint (avec issues correspondantes) |  https://github.com/Falsimane/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4/blob/main/Documentation/BacklogSprint2.adoc|
| 25/01/2023 |  Sprintboard |  https://github.com/users/Falsimane/projects/2/views/1|
| 25/01/2023 |  Cahier de tests |  https://github.com/Falsimane/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4/blob/main/Documentation/CahierDeTests.adoc|
| 27/01/2023 |  Documentation technique  | https://github.com/Falsimane/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4/blob/main/Documentation/documentation_technique.adoc|
| 27/01/2023 |  Documentation utilisateur | https://github.com/Falsimane/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-4/blob/main/Documentation/documentation_utilisateur.adoc|
|===

==== 2.2 Retour équipe projet 

Pour terminer ces deux semaines, nous allons écrire quelques mots sur ce qui a été notre deuxième sprint. Celui-ci a été comme le premier, accompagné de quelques difficultés. Il a en effet été assez compliqué pour nous de mettre en place l'intégration des PDF dans l'application. Néanmoins, après quelques heures passées sur ce problème, nous avons finalement réussi à trouver une solution. De plus, le pare-feu de l'IUT étant très restrictif, le déploiement d'un environnement de production n'a pas été possible. Toutefois, la très bonne entente entre les différents membres de l'équipe a été la source du bon déroulement de ce projet.  

En conclusion, ces deux semaines sont pour nous une réussite, que ce soit sur le plan technique ou organisationnel. Chaque membre a fourni un travail conséquent pour que toutes les fonctionnalités soient disponibles avant la fin du deuxième sprint. Enfin, une réunion avec le client a été tenue le 28/01 pour leur faire une démonstration du produit. Il semblerait qu'ils aient été très satisfait de l'application que nous leur avons proposée. Nous terminons donc ce projet de la meilleure des manières. 

==== 2.3 Retour sprint semaine 4
