version: "3"

services:
  nodered:
    image: nodered/node-red:3.0.2
    ports:
      - 8080:1880

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user


    



