version: "3"

services:
  nodered:
    image: node_tireuse
    ports:
      - 8080:1880

  influxdb:
    image: influx_tireuse
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user


    



