= Cahier de test - Janvier 2023
:icons: font
:experimental:
:toc:

== Introduction

=== 1. Présentation du produit

Le produit que nous allons tester est une application mobile de gestion d'une tireuse à bière connectée. Si vous souhaitez reproduire ces tests, il faudra tout d'abord mettre en place l'architecture de l'application. Pour cela, vous pouvez vous référer à la documentation technique.

=== 2. Prérequis

Pour pouvoir réaliser ces tests, il vous faudra :

* L'environnement de développement de l'application, ou l'application elle-même installée sur un smartphone Android
* L'environnement back-end mis en place, en local ou sur un serveur distant.

Pour toutes informations complémentaires, vous pouvez vous référer à la documentation technique disponible sur le dépôt Git.


== I. Cas de test :
=== 1. Fonctionnalités sur la page d'accueil :

|====

>|Cas de test 3+|Test-01
>|Titre 3+|Accéder à la page pour visualiser la puissance
>|Objectif 3+| Vérifier qu'il est possible d'accéder à la page pour visualiser la puissance

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "Puissance" ^|La fenêtre de visualisation de la puissance  s'affiche. ^|OK


|====

|====
|Cas de test 3+|Test-02

>|Cas de test 3+|Test-02
>|Titre 3+|Accéder à la page pour visualiser la quantité du fût
>|Objectif 3+| Vérifier qu'il est possible d'accéder à la page pour visualiser la quantité du fût

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "Quantité fût" ^|La fenêtre de visualisation de la quantité du fût s'affiche. ^|OK


|====

|====

>|Cas de test 3+|Test-03
>|Titre 3+|Accéder à la page pour visualiser la température du fût
>|Objectif 3+| Vérifier qu'il est possible d'accéder à la page pour visualiser la température du fût

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton (gauche) "Températures" ^|La fenêtre de visualisation de la température du fût s'affiche. ^|OK


|====

|====

>|Cas de test 3+|Test-04
>|Titre 3+|Accéder à la page pour visualiser la température ambiante
>|Objectif 3+| Vérifier qu'il est possible d'accéder à la page pour visualiser la température ambiante

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton (droite) "Températures" ^|La fenêtre de visualisation de la température ambiante s'affiche. ^|OK


|====

|====

>|Cas de test 3+|Test-05
>|Titre 3+|Accéder à la page pour visualiser l'emission de CO2
>|Objectif 3+| Vérifier qu'il est possible d'accéder à la page pour visualiser l'émission de CO2

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "CO2" ^|La fenêtre de visualisation de l'émission de CO2 s'affiche. ^|OK


|====

|====

>|Cas de test 3+|Test-06
>|Titre 3+|Accéder à la page de maintenance
>|Objectif 3+| Vérifier qu'il est possible d'accéder à la page de maintenance

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Swiper vers la droite ^|La fenêtre de la page de maintenance s'affiche. ^|OK

|====

|====

>|Cas de test 3+|Test-07
>|Titre 3+|Accéder à la page des paramètres
>|Objectif 3+| Vérifier qu'il est possible d'accéder à la page des paramètres

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur l'engrenage en haut à droite de la page ^|La fenêtre de la page des paramètres s'affiche. ^|OK

|====

=== 2. Fonctionnalités sur la page de maintenance :

|====

>|Cas de test 3+|Test-08
>|Titre 3+|Visualiser la notice d'utilisation
>|Objectif 3+| Vérifier qu'il est possible de visualiser la notice d'utilisation

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "notice d'utilisation" ^|La fenêtre de visualisation de la notice d'utilisation s'affiche^|OK

|====

|====

>|Cas de test 3+|Test-09
>|Titre 3+|Visualiser le manuel de service
>|Objectif 3+| Vérifier qu'il est possible de visualiser le manuel de service

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "manuel de service" ^|La fenêtre de visualisation du manuel de service s'affiche^|OK

|====

|====

>|Cas de test 3+|Test-10
>|Titre 3+|Visualiser les gammes préventives
>|Objectif 3+| Vérifier qu'il est possible de visualiser les gammes préventives

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "Maintenance préventive" ^|La fenêtre de la page de la maintenance préventive s'affiche^|OK
^|2 ^|Cliquer sur un bouton sur la page pour visualiser la gamme ^|La fenêtre de visualisation de la gamme s'affiche^|OK

|====

|====

>|Cas de test 3+|Test-11
>|Titre 3+|Visualiser les gammes curatives
>|Objectif 3+| Vérifier qu'il est possible de visualiser les gammes curatives

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "Maintenance curative" ^|La fenêtre de la page de la maintenance curative s'affiche ^|OK
^|2 ^|Cliquer sur un bouton sur la page pour visualiser la gamme ^|La fenêtre de visualisation de la gamme s'affiche ^|OK

|====

=== 3. Fonctionnalités sur la page de température :

|====

>|Cas de test 3+|Test-12
>|Titre 3+| Visualiser l'historique de la température
>|Objectif 3+| Vérifier qu'il est possible de visualiser l'historique de la température

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "Aujourd'hui" ^|L'historique de la température de la journée s'affiche^|OK
^|2 ^|Cliquer sur le bouton "Hier" ^|L'historique de la température de la veille s'affiche^|OK

|====

|====

>|Cas de test 3+|Test-13
>|Titre 3+| Visualiser l'état de la température
>|Objectif 3+| Vérifier si la température est correcte

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Arrivée sur la page température" ^|Un cercle de couleur doit être visible et changer selon l'état de la température^|OK
^|2 ^|Cliquer sur le bouton "(i)" ^|Les différents états disponibles avec les couleurs associées doivent s'afficher^|OK

|====

|====

>|Cas de test 3+|Test-14
>|Titre 3+| Vérifier l'état de la jauge
>|Objectif 3+| Vérifier si la température est correcte

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Arrivée sur la page température" ^|Une jauge de couleur doit être disponible et être en accord avec l'état de la température^|OK
|====

=== 4. Fonctionnalités sur la page puissance :

|====

>|Cas de test 3+|Test-15
>|Titre 3+| Visualiser l'historique de la puissance
>|Objectif 3+| Vérifier qu'il est possible de visualiser l'historique de la température

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "Aujourd'hui" ^|L'historique de la puissance de la journée s'affiche^|OK
^|2 ^|Cliquer sur le bouton "Hier" ^|L'historique de la puissance de la veille s'affiche^|OK

|====

|====

>|Cas de test 3+|Test-16
>|Titre 3+| Visualiser l'état de la puissance
>|Objectif 3+| Vérifier si la puissance est correcte

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Arrivée sur la page puissance" ^|Un cercle de couleur doit être visible et changer selon l'état de la puissance^|OK
^|2 ^|Cliquer sur le bouton "(i)" ^|Les différents états disponibles avec les couleurs associées doivent s'afficher^|OK

|====

|====

>|Cas de test 3+|Test-17
>|Titre 3+| Vérifier l'état de l'éclair
>|Objectif 3+| Vérifier si la puissance est correcte

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Arrivée sur la page température" ^|Un éclair doit être disponible et être en accord avec l'état de la température^|OK
|====

=== 4. Fonctionnalités sur la page Co2 :


|====

>|Cas de test 3+|Test-18
>|Titre 3+| Visualiser l'historique du Co2
>|Objectif 3+| Vérifier qu'il est possible de visualiser l'historique du Co2

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "Aujourd'hui" ^|L'historique du Co2 de la journée s'affiche^|OK
^|2 ^|Cliquer sur le bouton "Hier" ^|L'historique du Co2 de la veille s'affiche^|OK

|====

|====

>|Cas de test 3+|Test-19
>|Titre 3+| Visualiser l'état du Co2
>|Objectif 3+| Vérifier si l'air ambiant est sain

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Arrivée sur la page Co2" ^|Un cercle de couleur doit être visible et changer selon le niveau du Co2 dans l'air^|OK
^|2 ^|Cliquer sur le bouton "(i)" ^|Les différents états disponibles avec les couleurs associées doivent s'afficher^|OK

|====

|====

>|Cas de test 3+|Test-20
>|Titre 3+| Vérifier l'état de la terre
>|Objectif 3+| Vérifier si le niveau de Co2 dans l'air est correct

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Arrivée sur la page Co2" ^|Une terre (image) doit être disponible et être en accord avec l'état du Co2^|OK
|====

=== 4. Fonctionnalités sur la page Quantité Fût :

|====

>|Cas de test 3+|Test-21
>|Titre 3+| Visualiser l'historique de la quantité de bière
>|Objectif 3+| Vérifier qu'il est possible de visualiser l'historique de la quantité de bière

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "Aujourd'hui" ^|L'historique de la quantité de la journée s'affiche^|OK
^|2 ^|Cliquer sur le bouton "Hier" ^|L'historique de la quantité de la veille s'affiche^|OK

|====

|====

>|Cas de test 3+|Test-21
>|Titre 3+| Visualiser l'état de la bière dans le fût
>|Objectif 3+| Vérifier si le niveau de bière est correct

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Arrivée sur la page Quantité Fût" ^|Un cercle de couleur doit être visible et changer selon le niveau de bière dans le fût^|OK
^|2 ^|Cliquer sur le bouton "(i)" ^|Les différents états disponibles avec les couleurs associées doivent s'afficher^|OK

|====

|====

>|Cas de test 3+|Test-22
>|Titre 3+| Vérifier l'état du fût
>|Objectif 3+| Vérifier si le niveau de de bière est correct

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Arrivée sur la page Quantité Fût" ^|Un fût (image) doit être disponible et être en accord avec l'état du taux de remplissage^|OK
|====
