= Cahier de test - Janvier 2023
:icons: font
:experimental:
:toc:

== Introduction

=== 1. Présentation du produit

Le produit que nous allons tester est une application mobile de gestion d'une tireuse à bière connectée. Si vous souhaitez reproduire ces tests, il faudra tout d'abord mettre en place l'architecture de l'application. Pour cela, vous pouvez vous référer à la documentation technique.

=== 2. Prérequis

Pour pouvoir réaliser ces tests, il vous faudra :

* L'environnement de développement de l'application, ou l'application elle-même installée sur un smartphone Android
* L'environnement back-end mis en place, en local ou sur un serveur distant.

Pour toutes informations complémentaires, vous pouvez vous référer à la documentation technique disponible sur le dépôt Git.


== I. Cas de test :
=== 1. Fonctionnalités sur la page d'accueil :

|====

>|Cas de test 3+|Test-01-01-01
>|Titre 3+|Accéder à la page pour visualiser la puissance
>|Objectif 3+| Vérifier qu'il est possible d'accéder à la page pour visualiser la puissance

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "Puissance" ^|La fenêtre de visualisation de la puissance  s'affiche. ^|OK


|====

